In [12]:

#list - List items are ordered, changeable, and allow duplicate values.
customers1 = ["FirstCust","FavCust","LoyalCust","ForLifeCust","GoodCust"]
for cust in customers1:
    print (cust)

FirstCust
FavCust
LoyalCust
ForLifeCust
GoodCust


In [6]:
customers2 = list(("FirstCust","FavCust","LoyalCust","ForLifeCust"))
for cust in customers2:
    print (cust)

FirstCust
FavCust
LoyalCust
ForLifeCust


In [8]:
print(customers1[2])

LoyalCust


In [14]:

#This will return the items from index 1, 2 , 3 excluding index 4.

print (customers1[1:4])

['FavCust', 'LoyalCust', 'ForLifeCust']


In [16]:
#This will return the items from index 0 to index 2.

#Remember that index 0 is the first item, and index 1 is the second item
#Remember that the item in index 2 is NOT included
print (customers1[:2])

['FirstCust', 'FavCust']


In [18]:
#replace a item
customers1[2] = "DailyCustomer"
print(customers1)

['FirstCust', 'FavCust', 'DailyCustomer', 'ForLifeCust', 'GoodCust']


In [19]:
#add a item
customers1.append("NewCustomer")
print(customers1)

['FirstCust', 'FavCust', 'DailyCustomer', 'ForLifeCust', 'GoodCust', 'NewCustomer']


In [20]:
#remove a item by value
customers1.remove("FavCust")
print(customers1)

#remove a item by index
customers1.pop(3)
print(customers1)



['FirstCust', 'DailyCustomer', 'ForLifeCust', 'GoodCust', 'NewCustomer']
['FirstCust', 'DailyCustomer', 'ForLifeCust', 'NewCustomer']


In [22]:
# dele keyword to delete using index
del customers1[0]
print(customers1)

['ForLifeCust', 'NewCustomer']


In [24]:
del customers1 # delete fulllist
print(customers1)

NameError: name 'customers1' is not defined

In [37]:
customers1 = ["FirstCust","FavCust","LoyalCust","ForLifeCust","GoodCust"]
# iterate using index and range
for i in range(len(customers1)):
    print (customers1[i])

if "LoyalCust" in  customers1:
    print("Loyal Customer Present in List")

FirstCust
FavCust
LoyalCust
ForLifeCust
GoodCust
Loyal Customer Present in List


In [27]:
mylist1 = [30,20,10,15,5,4,31,21,22,24]
mylist1.sort()
print (mylist1)

[4, 5, 10, 15, 20, 21, 22, 24, 30, 31]


In [29]:
mylist1.sort(reverse=True)
print (mylist1)

[31, 30, 24, 22, 21, 20, 15, 10, 5, 4]


In [30]:
#return number closet to 50
def myComp(num):
    return abs(num -50)

mylist2 = [60,50,49,15,5,4,31,21,22,24]
mylist2.sort(key=myComp)
print(mylist2)
    

[50, 49, 60, 31, 24, 22, 21, 15, 5, 4]


In [32]:
#set - A set is a collection which is unordered, unchangeable*, and unindexed. Once a set is created, you cannot change its items, but you can add new items.
myset = {"apple", "banana", "cherry"}
print (myset)

for x in myset:
  print(x)

{'apple', 'cherry', 'banana'}
apple
cherry
banana


In [33]:
# tuple - A tuple is a collection which is ordered and unchangeable.Tuple items are indexed, the first item has index [0], the second item has index [1] etc.

thistuple = ("apple", "banana", "cherry")
print(thistuple)

('apple', 'banana', 'cherry')


In [34]:
# A tuple with strings, integers and boolean values:
tuple1 = ("abc", 34, True, 40, "male")
print(tuple1)

('abc', 34, True, 40, 'male')


In [35]:
# Access tuple
thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[2:5])

('cherry', 'orange', 'kiwi')


In [38]:
# in clause for check in collection/tuple
thistuple = ("apple", "banana", "cherry")
if "apple" in thistuple:
  print("Yes, 'apple' is in the fruits tuple")

Yes, 'apple' is in the fruits tuple


In [40]:
# Dictionaries are written with curly brackets, and have keys and values:
# Dictionaries cannot have two items with the same key:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

x = thisdict.get("model")
print(x)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
Mustang


In [42]:
# Add new keys
x = thisdict.keys()

print(x) #before the change

thisdict["color"] = "white"

print(x) #after the change

dict_keys(['brand', 'model', 'year'])
dict_keys(['brand', 'model', 'year', 'color'])


In [45]:
# Replace values to keys in dict
x = thisdict.values()

print(x) #before the change

thisdict["year"] = 2020

print(x) #after the change

dict_values(['Ford', 'Mustang', 2020, 'white'])
dict_values(['Ford', 'Mustang', 2020, 'white'])


In [46]:
# print keys
for x in thisdict:
  print(x)

# print values
for x in thisdict:
  print(thisdict[x])

brand
model
year
color
Ford
Mustang
2020
white


In [47]:
#Loop through both keys and values, by using the items() method:
for x, y in thisdict.items():
  print(x, y)


brand Ford
model Mustang
year 2020
color white


In [48]:
# Make a copy of a dictionary with the copy() method:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
mydict = thisdict.copy()
print(mydict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [49]:
# Nested Disctionaries
child1 = {
  "name" : "Emil",
  "year" : 2004
}
child2 = {
  "name" : "Tobias",
  "year" : 2007
}
child3 = {
  "name" : "Linus",
  "year" : 2011
}

myfamily = {
  "child1" : child1,
  "child2" : child2,
  "child3" : child3
}

print(myfamily["child2"]["name"])

Tobias


In [50]:
# A lambda function is a small anonymous function.
# A lambda function can take any number of arguments, but can only have one expression.

x = lambda a : a + 10
print(x(5))



15


In [51]:
#The power of lambda is better shown when you use them as an anonymous function inside another function.

# Say you have a function definition that takes one argument, and that argument will be multiplied with an unknown number: 
# which means you can define a dynamic function based on lambada expression which can take differnt fuctionality based on values and then called
# for different inputs 

def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)

print(mydoubler(11))


22


In [52]:
# list of dictionaries
# create a list of dictionary with student
# id as key and name as value
data = [{7058: 'sravan', 7059: 'jyothika',
         7072: 'harsha', 7075: 'deepika'}]

# display data
print(data)
print(len(data))
print(type(data))

[{7058: 'sravan', 7059: 'jyothika', 7072: 'harsha', 7075: 'deepika'}]
1
<class 'list'>


In [53]:
# display data of key 7058
print(data[0][7058])

sravan


In [54]:


# create a list of a dictionary
# with single dictionary element
data = [ {1: "Geeks", 2: "GeeksforGeeks"} ]
print(data)
 
# create a new dictionary to be appended
new_data = {1: "Python", 2: "Programming"}
 
# appending the new dictionary to
# the original list of dictionary
data.append(new_data)
print(data)

[{1: 'Geeks', 2: 'GeeksforGeeks'}]
[{1: 'Geeks', 2: 'GeeksforGeeks'}, {1: 'Python', 2: 'Programming'}]


In [55]:
# Filtering list dictionary example
data = [
    {'name': 'Alice', 'age': 25},
    {'name': 'Bob', 'age': 30},
    {'name': 'Charlie', 'age': 22},
    {'name': 'David', 'age': 35}
]

filtered_data = []
for entry in data:
    if entry['age'] > 25:
        filtered_data.append(entry)
 
print(filtered_data)

[{'name': 'Bob', 'age': 30}, {'name': 'David', 'age': 35}]


In [56]:
# Filter List Of Dictionaries Based On Key Value Using the Filter Function
# The filter function is a built-in Python function that constructs an iterator from elements of an iterable for which a function returns true. 
# To use it with a list of dictionaries, we need a filtering function. Here’s an example:

# Filtering function
def filter_by_age(entry):
    return entry['age'] > 25
 
# Using filter function
filtered_data = list(filter(filter_by_age, data))
 
print(filtered_data)

[{'name': 'Bob', 'age': 30}, {'name': 'David', 'age': 35}]


In [57]:
#JSON
#Convert from JSON to Python:
import json

# some JSON:
x =  '{ "name":"John", "age":30, "city":"New York"}'

# parse x:
y = json.loads(x)

# the result is a Python dictionary:
print(y["age"])

30


In [58]:
# Convert from Python to JSON:
import json

# a Python object (dict):
x = {
  "name": "John",
  "age": 30,
  "city": "New York"
}

# convert into JSON:
y = json.dumps(x)

# the result is a JSON string:
print(y)

{"name": "John", "age": 30, "city": "New York"}


In [61]:
# regex
import re

txt = "The rain in Spain"
x = re.search("^The.*Spain$", txt)
print(x)

if x:
  print("YES! We have a match!")
else:
  print("No match")


<re.Match object; span=(0, 17), match='The rain in Spain'>
YES! We have a match!


In [62]:
#Find all lower case characters alphabetically between "a" and "m":

x = re.findall("[a-m]", txt)
print(x)


['h', 'e', 'a', 'i', 'i', 'a', 'i']


In [64]:
# file handling 

f = open("demofile.txt", "r")
print(f.read())

Hello! Welcome to demofile.txt
This file is for testing purposes.
Good Luck!


In [65]:
f = open("demofile.txt", "r")
print(f.readline())

Hello! Welcome to demofile.txt



In [66]:
f = open("demofile.txt", "r")
print(f.readline())
f.close()

Hello! Welcome to demofile.txt



In [67]:
f = open("demofile2.txt", "a")
f.write("Now the file has more content!")
f.close()

#open and read the file after the appending:
f = open("demofile2.txt", "r")
print(f.read())

Now the file has more content!


In [68]:
#numpy
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [69]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [70]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [71]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [72]:
#Join 2D array along x axis
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [73]:
# stack
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [74]:
# In NumPy, you filter an array using a boolean index list.
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [1]:
# Pandas
import pandas

# dictionary with key and list
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

# pandas will give Dataframe
myvar = pandas.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [2]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64


In [4]:
# print using index label when label is not specified
print(myvar[0])
print(myvar[1])
print(myvar[2])


1
7
2


In [6]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

# print with specified index label
print(myvar)

x    1
y    7
z    2
dtype: int64


In [7]:
# series from key val object, keys are treated as label
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64


In [10]:
#Data sets in Pandas are usually multi-dimensional tables, called DataFrames.

#Series is like a column, a DataFrame is the whole table.


import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data)

print(myvar)



   calories  duration
0       420        50
1       380        40
2       390        45


In [11]:
#refer to the row index:
print(df.loc[0])

calories    420
duration     50
Name: 0, dtype: int64


In [13]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df) 

#refer to the named index:
print(df.loc["day2"])

      calories  duration
day1       420        50
day2       380        40
day3       390        45
calories    380
duration     40
Name: day2, dtype: int64


In [14]:
#load csv using pandas
import pandas as pd

df = pd.read_csv('data.csv')

print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0


In [16]:
import pandas as pd

df = pd.read_json('data.json')

print(df.to_string()) 

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.5
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

In [17]:
import pandas as pd

data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df) 

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300
